from typing import List, Any

# -------------------------
# Code generation (Vertex AST -> Python source)
# -------------------------
def codegen_expr(node) -> str:
    t = node[0]
    if t == 'number':
        v = node[1]
        # print integers as integers when possible
        if int(v) == v:
            return str(int(v))
        return repr(v)
    if t == 'string':
        return repr(node[1])
    if t == 'var':
        return node[1]
    if t == 'binop':
        _, op, left, right = node

        # Use runtime helper for addition to handle string concatenation
        if op == 'PLUS':
            return f"_v_add({codegen_expr(left)}, {codegen_expr(right)})"

        op_map = {
            'MINUS': '-', 'MULT': '*', 'DIV': '/',
            'EQ': '==', 'NEQ': '!=', 'LT': '<', 'GT': '>', 'LTE': '<=', 'GTE': '>='
        }
        pyop = op_map.get(op, op)
        return f"({codegen_expr(left)} {pyop} {codegen_expr(right)})"

    raise RuntimeError(f"Unknown expr node: {node}")

def codegen_stmt(stmt, indent=0) -> str:
    indent_str = "    " * indent
    t = stmt[0]
    if t == 'let':
        _, name, var_type, expr = stmt
        # we ignore var_type in this MVP; you can add runtime checks later
        return f"{indent_str}{name} = {codegen_expr(expr)}"
    if t == 'assign':
        _, name, expr = stmt
        return f"{indent_str}{name} = {codegen_expr(expr)}"
    if t == 'print':
        _, expr = stmt
        return f"{indent_str}print({codegen_expr(expr)})"
    if t == 'if':
        _, cond, then_block, else_block = stmt
        lines = []
        lines.append(f"{indent_str}if {codegen_expr(cond)}:")
        if not then_block:
            lines.append(f"{indent_str}    pass")
        else:
            for s in then_block:
                lines.append(codegen_stmt(s, indent + 1))

        if else_block:
            lines.append(f"{indent_str}else:")
            for s in else_block:
                lines.append(codegen_stmt(s, indent + 1))
        return "\n".join(lines)
    if t == 'while':
        _, cond, block = stmt
        lines = []
        lines.append(f"{indent_str}while {codegen_expr(cond)}:")
        if not block:
            lines.append(f"{indent_str}    pass")
        else:
            for s in block:
                lines.append(codegen_stmt(s, indent + 1))
        return "\n".join(lines)

    raise RuntimeError(f"Unknown stmt node: {stmt}")

def compile_to_python(ast: List[Any], module_name: str = None) -> str:
    lines = []
    lines.append("# Generated by Vertex compiler (MVP)")
    lines.append("import sys")
    lines.append("")

    # Runtime helper for dynamic string concatenation
    lines.append("def _v_add(a, b):")
    lines.append("    if isinstance(a, str) or isinstance(b, str):")
    lines.append("        return str(a) + str(b)")
    lines.append("    return a + b")
    lines.append("")

    for s in ast:
        lines.append(codegen_stmt(s))
    lines.append("")
    return "\n".join(lines)
